[package]
name = "html5ever-glue"
version = "0.1.0"
authors = ["Theodore Dubois <tblodt@icloud.com>"]

[lib]
name = "html5ever_glue"
path = "glue.rs"
crate-type = ["staticlib"]
test = false

[dependencies]
libc = "0.2.28"
html5ever = "0.18"
string_cache = "0.6"
